dist: xenial

language: python
python:
  - 3.8

env:
  global:
    # Doctr deploy key for keurfonluu/disba
    - secure: "hQWqBXJ9TIs0mmoUrjCwIXmqALW0zltGrLZB/K27BNWQAvoRXbVL/n02+nSKQSSNhGZd+hMZ9g0QElmWgdphfhbs/ls5jTPxQiyi56g/ViWgBHgHaD0BcyBvplqjyXL2VrKu4Sz8Xh4xo/ybfNRpl2Pe2Grybr9pgyiI1Ut72QnMRh6/kFmteazs5bCt7HVEUywAymKpxeV7xejzga4cKu47GxFjPIGjjrLE8rd1F31QUtmbL3RzLdmIZpbTJXRU7VfF/6y2opi0BquSqpitiI+a5LkUOVMecu/74LnJNj078cgYQtVxV805IjOEDbRtnvVIveTor53YpqQ5Upvx4BMLUJlllWM0EqUzeGYy6skx3pKQ4NOJ2q7TOJAx7OudRqg48yZzlsOUtCK4bVvr57fk+CI0L1n5qGQFr1f27/QuesJVty5iaNgfEj96W77xwwEmLeMeQiwWykwARc9F8X32vcmfQBm0e/lALv/raPG4zyKtV3FhD9NqG0jnRB5QArOtQgF19c1s+Ty3WbI0/K2tWE+3XJTKQ2IxtNOcAJ06VtuCKjVu3sr0LPxaO5JWj6CZQ7tK5MzXQ/rrXFjk1wImDlB1Ixpw8qd+luaur3UWla8Ynbh8N8sGNfvEP9AnbSGyiT6McLmmdzYRJxXo/6k6Ti6uSgrdKlZd7MZ9T4c="

install:
  - pip install .
  - pip install scipy
  - pip install -r doc/requirements.txt

script:
  - set -e
  - sphinx-build -b html doc/source doc/build
  - pip install doctr
  - doctr deploy . --built-docs ./doc/build/